#!/bin/sh

echo '🏗️👷 Testing and building your project before committing..'

# Check Prettier standards
npm run check || {
    echo 'Prettier Check Failed. Run "npm run format", add changes and try commit again.' 
    false
}

# Check ESLint Standards
npm run lint || {
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false
}